#server:
#  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'